name: screen_tracker
description: Away to track all screens. In Karee project, to track all screen and generate associated files for fast usage, we choose to make a tracker.
version: 2.0.0
homepage: https://github.com/ChamplainLeCode/karee_screen_tracker.git
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
 
dev_dependencies:
  test: 1.3.4